this my solution
alwanof/PAG1 pull request #6
Opened 2023-03-04 18:24 UTC by AhmedOmar11122

2023-03-04 20:50 UTC, AhmedOmar11122 commented
this task

2023-03-04 21:25 UTC, alwanof reviewed
صلح السطر الاول 
<?php

2023-03-04 21:40 UTC, AhmedOmar11122 commented
تمام استاذ

2023-03-04 21:41 UTC, AhmedOmar11122 commented
تمام استاذ

2023-03-05 05:34 UTC, alwanof commented on src/PAG1.php
> -<?php
صحح هذا السطر ارجوك

2023-03-05 05:35 UTC, alwanof requested changes

2023-03-05 05:35 UTC, alwanof commented on src/PAG1.php
> -<?php
صحح هذا السطر

2023-03-06 11:39 UTC, closed without merging